export const HEADER_BTNS_TEXT = [
  "Toate produsele",
  "Credit imobiliar - ipotecar",
  "Credit de nevoi personale (4)",
  "Card STAR (3)",
  "Festival Stuff",
  "Pachet Credit nevoi dobanda fixa + Card STAR (3)",
  "Pachet Credit nevoi dobanda variabila + Card STAR (3)",
  "Leasing auto (2)",
];

export const CARD_DATA = [
  {
    id: 1,
    cardPhotoSrc: "./assets/photo1.png",
    cardTitle: "Card de debit Mastercard Gold",
    cardParaOne: "Dobanda fixa: 7,5%",
    cardParaTwo: "250 puncte STAR",
    cardBtnText: "VEZI OFERTA",
  },
  {
    id: 2,
    cardPhotoSrc: "./assets/photo2.png",
    cardTitle: "Card de debit Mastercard Gold",
    cardParaOne: "Dobanda fixa: 7,5%",
    cardParaTwo: "250 puncte STAR",
    cardBtnText: "VEZI OFERTA",
  },
  {
    id: 3,
    cardPhotoSrc: "./assets/photo3.png",
    cardTitle: "Card Flying Blue Premium",
    cardParaOne: "Dobanda fixa: 7,5%",
    cardParaTwo: "250 puncte STAR",
    cardBtnText: "VEZI OFERTA",
  },
  {
    id: 4,
    cardPhotoSrc: "./assets/photo4.png",
    cardTitle: "Card STAR FORTE",
    cardParaOne: "Dobanda fixa: 7,5%",
    cardParaTwo: "250 puncte STAR",
    cardBtnText: "VEZI OFERTA",
  },
  {
    id: 5,
    cardPhotoSrc: "./assets/photo5.png",
    cardTitle: "",
    cardParaOne: "",
    cardParaTwo: "",
    cardBtnText: "",
  },
  {
    id: 6,
    cardPhotoSrc: "./assets/photo6.png",
    cardTitle: "Card STAR GOLD",
    cardParaOne: "Dobanda fixa: 7,5%",
    cardParaTwo: "250 puncte STAR",
    cardBtnText: "VEZI OFERTA",
  },
  {
    id: 7,
    cardPhotoSrc: "./assets/photo7.png",
    cardTitle: "Credit de nevoi personale cu dobândă fixă și asigurare",
    cardParaOne: "Dobanda fixa: 7,5%",
    cardParaTwo: "250 puncte STAR",
    cardBtnText: "VEZI OFERTA",
  },
  {
    id: 8,
    cardPhotoSrc: "./assets/photo8.png",
    cardTitle: "Credit de nevoi personale cu dobândă fixă",
    cardParaOne: "Dobanda fixa: 7,5%",
    cardParaTwo: "250 puncte STAR",
    cardBtnText: "VEZI OFERTA",
  },
  {
    id: 9,
    cardPhotoSrc: "./assets/photo9.png",
    cardTitle: "Credit de nevoi personale cu dobândă variabilă și asigurare",
    cardParaOne: "Dobanda fixa: 7,5%",
    cardParaTwo: "250 puncte STAR",
    cardBtnText: "VEZI OFERTA",
  },
  {
    id: 10,
    cardPhotoSrc: "./assets/photo10.png",
    cardTitle: "Credit de nevoi personale cu dobândă variabilă",
    cardParaOne: "Dobanda fixa: 7,5%",
    cardParaTwo: "250 puncte STAR",
    cardBtnText: "VEZI OFERTA",
  },
  {
    id: 11,
    cardPhotoSrc: "./assets/photo11.png",
    cardTitle: "Credit imobiliar-ipotecar",
    cardParaOne: "Dobanda fixa: 7,5%",
    cardParaTwo: "250 puncte STAR",
    cardBtnText: "VEZI OFERTA",
  },
  {
    id: 12,
    cardPhotoSrc: "./assets/photo12.png",
    cardTitle: "EXTRA Leasing auto",
    cardParaOne: "Dobanda fixa: 7,5%",
    cardParaTwo: "250 puncte STAR",
    cardBtnText: "VEZI OFERTA",
  },
  {
    id: 13,
    cardPhotoSrc: "./assets/photo13.png",
    cardTitle: "Omnipass",
    cardParaOne: "Dobanda fixa: 7,5%",
    cardParaTwo: "250 puncte STAR",
    cardBtnText: "VEZI OFERTA",
  },
  {
    id: 14,
    cardPhotoSrc: "./assets/photo14.png",
    cardTitle: "Overdraft",
    cardParaOne: "Dobanda fixa: 7,5%",
    cardParaTwo: "250 puncte STAR",
    cardBtnText: "VEZI OFERTA",
  },
  {
    id: 15,
    cardPhotoSrc: "./assets/photo15.png",
    cardTitle: "Pachet CRD Nev Pers | card STAR Forte  | Gold",
    cardParaOne: "Dobanda fixa: 7,5%",
    cardParaTwo: "250 puncte STAR",
    cardBtnText: "VEZI OFERTA",
  },
  {
    id: 16,
    cardPhotoSrc: "./assets/photo16.png",
    cardTitle: "Pachet credit nevoi personale cu dobândă fixă + card STAR",
    cardParaOne: "Dobanda fixa: 7,5%",
    cardParaTwo: "250 puncte STAR",
    cardBtnText: "VEZI OFERTA",
  },
  {
    id: 17,
    cardPhotoSrc: "./assets/photo17.png",
    cardTitle: "Pachet credit nevoi personale cu dobândă variabilă + card STAR",
    cardParaOne: "Dobanda fixa: 7,5%",
    cardParaTwo: "250 puncte STAR",
    cardBtnText: "VEZI OFERTA",
  },
];
